fix: Fixed signature path

diff --git a/.github/workflows/pyinstaller.yml b/.github/workflows/pyinstaller.yml
--- a/.github/workflows/pyinstaller.yml
+++ b/.github/workflows/pyinstaller.yml
@@ -47,11 +47,20 @@ jobs:
           echo "Checking dist/ directory..."
           dir dist  # List contents of dist/ folder to confirm EXE is created
 
+      - name: Create Certificate
+        run: |
+          cd TribalWars/Staff-Scripts/TWRankings
+          if (Test-Path "dist\TWRankings*.exe") {
+            "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /a /tr http://timestamp.digicert.com /fd SHA256 /td SHA256 /v dist\TWRankings*.exe
+          } else {
+            echo "ERROR: EXE not found!"
+            exit 1
+          }
+
       - name: Commit and push EXE if it exists
         run: |
-          cd TribalWars/Staff-Scripts/TWRankings  # Move to the directory where the script is
+          cd TribalWars/Staff-Scripts/TWRankings
           if (Test-Path "dist\TWRankings*.exe") {
-            signtool sign /a /tr http://timestamp.digicert.com /fd SHA256 /td SHA256 /v dist\TWRankings*.exe
             echo "EXE found, committing..."
             git config --global user.name "github-actions"  
             git config --global user.email "actions@github.com"  
